"""initial

Revision ID: 2306b1fb0742
Revises: 
Create Date: 2025-12-14 20:22:35.503083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID

# revision identifiers, used by Alembic.
revision: str = '2306b1fb0742'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('anthropic', 'zai', 'openrouter', name='modelprovider'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_models_provider_active', 'ai_models', ['provider', 'is_active'], unique=False)
    op.create_index('idx_ai_models_sort_order', 'ai_models', ['sort_order'], unique=False)
    op.create_index(op.f('ix_ai_models_model_id'), 'ai_models', ['model_id'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('daily_message_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email_verified', 'users', ['email', 'is_verified'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('context_token_usage', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chats_user_id_deleted_at', 'chats', ['user_id', 'deleted_at'], unique=False)
    op.create_index('idx_chats_user_id_id', 'chats', ['user_id', 'id'], unique=False)
    op.create_index('idx_chats_user_id_pinned_at', 'chats', ['user_id', 'pinned_at'], unique=False)
    op.create_index('idx_chats_user_id_sandbox_id', 'chats', ['user_id', 'sandbox_id'], unique=False)
    op.create_index('idx_chats_user_id_updated_at_desc', 'chats', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_token_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_message', sa.Text(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('once', 'daily', 'weekly', 'monthly', name='recurrencetype'), nullable=False),
    sa.Column('scheduled_time', sa.String(length=8), nullable=False),
    sa.Column('scheduled_day', sa.Integer(), nullable=True),
    sa.Column('next_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_execution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'paused', 'completed', 'failed', name='taskstatus'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('permission_mode', sa.String(), nullable=False),
    sa.Column('thinking_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_tasks_enabled_next', 'scheduled_tasks', ['enabled', 'next_execution'], unique=False)
    op.create_index('idx_scheduled_tasks_user_next', 'scheduled_tasks', ['user_id', 'next_execution'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_next_execution'), 'scheduled_tasks', ['next_execution'], unique=False)
    op.create_index(op.f('ix_scheduled_tasks_user_id'), 'scheduled_tasks', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('github_personal_access_token', sa.String(), nullable=True),
    sa.Column('e2b_api_key', sa.String(), nullable=True),
    sa.Column('claude_code_oauth_token', sa.String(), nullable=True),
    sa.Column('z_ai_api_key', sa.String(), nullable=True),
    sa.Column('openrouter_api_key', sa.String(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('custom_agents', sa.JSON(), nullable=True),
    sa.Column('custom_mcps', sa.JSON(), nullable=True),
    sa.Column('custom_env_vars', sa.JSON(), nullable=True),
    sa.Column('custom_skills', sa.JSON(), nullable=True),
    sa.Column('custom_slash_commands', sa.JSON(), nullable=True),
    sa.Column('notification_sound_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('chat_id', GUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole'), nullable=False),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=40), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('stream_status', sa.Enum('in_progress', 'completed', 'failed', 'interrupted', name='messagestreamstatus'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_chat_id_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_messages_chat_id_deleted_at', 'messages', ['chat_id', 'deleted_at'], unique=False)
    op.create_index('idx_messages_chat_id_role_deleted', 'messages', ['chat_id', 'role', 'deleted_at'], unique=False)
    op.create_index('idx_messages_role_created', 'messages', ['role', 'created_at'], unique=False)
    op.create_index('idx_messages_stream_status', 'messages', ['stream_status'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('task_id', GUID(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='taskexecutionstatus'), nullable=False),
    sa.Column('chat_id', GUID(), nullable=True),
    sa.Column('message_id', GUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_executions_status', 'task_executions', ['status'], unique=False)
    op.create_index('idx_task_executions_task_created', 'task_executions', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_task_executions_task_id'), 'task_executions', ['task_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('message_id', GUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'pdf', 'xlsx', name='attachmenttype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_task_executions_task_id'), table_name='task_executions')
    op.drop_index('idx_task_executions_task_created', table_name='task_executions')
    op.drop_index('idx_task_executions_status', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('idx_messages_stream_status', table_name='messages')
    op.drop_index('idx_messages_role_created', table_name='messages')
    op.drop_index('idx_messages_chat_id_role_deleted', table_name='messages')
    op.drop_index('idx_messages_chat_id_deleted_at', table_name='messages')
    op.drop_index('idx_messages_chat_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_scheduled_tasks_user_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_next_execution'), table_name='scheduled_tasks')
    op.drop_index('idx_scheduled_tasks_user_next', table_name='scheduled_tasks')
    op.drop_index('idx_scheduled_tasks_enabled_next', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index('idx_chats_user_id_updated_at_desc', table_name='chats')
    op.drop_index('idx_chats_user_id_sandbox_id', table_name='chats')
    op.drop_index('idx_chats_user_id_pinned_at', table_name='chats')
    op.drop_index('idx_chats_user_id_id', table_name='chats')
    op.drop_index('idx_chats_user_id_deleted_at', table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_email_verified', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ai_models_model_id'), table_name='ai_models')
    op.drop_index('idx_ai_models_sort_order', table_name='ai_models')
    op.drop_index('idx_ai_models_provider_active', table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
